package com.example.queueview.data.model

import com.google.firebase.Timestamp

data class QueueData(
    val id: String = "",  // Auto-generated by Firestore
    val placeName: String = "",
    val placeType: String = "BANK",  // Can be "BANK", "RESTAURANT", "HOSPITAL"
    val latitude: Double = 0.0,
    val longitude: Double = 0.0,
    val waitingTime: Int = 0,  // in minutes
    val lastUpdated: Timestamp = Timestamp.now(),
    val submittedBy: String? = null  // Firebase User ID (optional)
){

    fun toMap():Map<String, Any?> {
        return mapOf(
            "placeName" to placeName,
            "placeType" to placeType,
            "latitude" to latitude,
            "longitude" to longitude,
            "waitingTime" to waitingTime,
            "lastUpdated" to lastUpdated,
            "submittedBy" to submittedBy
        )
    }
}
